swagger: "2.0"
info:
  description: Something about the API
  version: "1.0.0"
  title: My Cool API
basePath: "/api/v1"
schemes:
  - "https"
paths:
  /ping:
    get:
      tags:
        - "root"
      summary: "Get Server Information"
      operationId: "ping"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ServerInfo"
  /things:
    get:
      tags:
        - "root"
      summary: "Get Server Information"
      operationId: "things"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ArrayOfThings"
      security:
      - slack:
        - "identity.basic"
        - "identity.email"
  /thingsABC:
    get:
      summary: "Find things"
      description: "Returns a list of things"
      operationId: "v1/things/listThings"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ArrayOfThings"
      security:
      - slack:
        - "identity.basic"
        - "identity.email"
definitions:
  ServerInfo:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"
  ArrayOfThings:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"